name: Publish Docker
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@cade1bc
        with:
          name: ihciah/rabbit
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}